name: PR Verifier
on:
  pull_request_target:
    types: [opened, edited, reopened]
jobs:
  verify:
    name: Verify PR contents
    runs-on: ubuntu-latest
    steps:
    - name: Verifier action
      id: verifier
      run: python -m pip install --upgrade pip
    - id: checkout
      uses: actions/checkout@v2
